### ISSUE TITLE
#miss build

### ISSUE THREAD

**Issue by mcuhf** [IvanBongiorni/GAN-RNN_Timeseries-imputation#1]
Hello! 
I just find that name 'build' is not defined.
It is about generator model.
wish your reply！

**Comment by IvanBongiorni** [comment]
Hello,
yes, you're right. At the moment I'm training the "Vanilla" seq2seq version (the non-GAN model), I made a lot of changes to the code and that's why there's not build() anymore.

Once the Vanilla model is implemented and tested (I should make it in few days) I will start working on the GAN version, and I will correct that for sure.

Thanks for noticing!

**Comment by IvanBongiorni** [comment]
It's all fixed with the latest push, thanks again for noticing
